TOKEN: RESERVED <?php
TOKEN: FUNCTION session_start(
TOKEN: PUNTUACTION )
TOKEN: PUNTUACTION ;
TOKEN: FUNCTION unset(
TOKEN: VAR $_SESSION
TOKEN: PUNTUACTION [
TOKEN: STRING "username"
TOKEN: PUNTUACTION ]
TOKEN: PUNTUACTION )
TOKEN: PUNTUACTION ;
TOKEN: FUNCTION unset(
TOKEN: VAR $_SESSION
TOKEN: PUNTUACTION [
TOKEN: STRING "password"
TOKEN: PUNTUACTION ]
TOKEN: PUNTUACTION )
TOKEN: PUNTUACTION ;
TOKEN: RESERVED echo
TOKEN: STRING 'You have cleaned session'
TOKEN: PUNTUACTION ;
TOKEN: FUNCTION header(
TOKEN: STRING 'Refresh: 2; URL = login.php'
TOKEN: PUNTUACTION )
TOKEN: PUNTUACTION ;
TOKEN: RESERVED ?>
TOKEN: RESERVED <?php
TOKEN: VAR $foo
TOKEN: LOGIC_OPERATOR =
TOKEN: BOOLEAN True
TOKEN: PUNTUACTION ; 
TOKEN: COMMENT // asigna el valor TRUE a $foo
TOKEN: VAR $foo
TOKEN: LOGIC_OPERATOR =
TOKEN: BOOLEAN False
TOKEN: PUNTUACTION ; 
TOKEN: COMMENT // asigna el valor False a $foo
TOKEN: RESERVED ?>
TOKEN: RESERVED <?php
TOKEN: VAR $a
TOKEN: LOGIC_OPERATOR =
TOKEN: INT 1234
TOKEN: PUNTUACTION ; 
TOKEN: COMMENT // número decimal
TOKEN: VAR $a
TOKEN: LOGIC_OPERATOR =
TOKEN: INT -123
TOKEN: PUNTUACTION ; 
TOKEN: COMMENT // un número negativo
TOKEN: VAR $a
TOKEN: LOGIC_OPERATOR =
TOKEN: INT 0123
TOKEN: PUNTUACTION ; 
TOKEN: COMMENT // número octal (equivale a 83 decimal)
TOKEN: VAR $a
TOKEN: LOGIC_OPERATOR =
TOKEN: INT 0x1A
TOKEN: PUNTUACTION ; 
TOKEN: COMMENT // número hexadecimal (equivale a 26 decimal)
TOKEN: VAR $a
TOKEN: LOGIC_OPERATOR =
TOKEN: INT 0b11111111
TOKEN: PUNTUACTION ; 
TOKEN: COMMENT // número binario (equivale al 255 decimal)
TOKEN: RESERVED ?>
TOKEN: RESERVED <?php
TOKEN: VAR $a
TOKEN: LOGIC_OPERATOR =
TOKEN: FLOAT 1.234
TOKEN: PUNTUACTION ; 
TOKEN: VAR $b
TOKEN: LOGIC_OPERATOR =
TOKEN: FLOAT 1.2e3
TOKEN: PUNTUACTION ; 
TOKEN: VAR $c
TOKEN: LOGIC_OPERATOR =
TOKEN: FLOAT 7E-10
TOKEN: PUNTUACTION ;
TOKEN: RESERVED ?>
TOKEN: RESERVED <?php
TOKEN: ID Este_identificador_es_valido
TOKEN: ID _este_también
TOKEN: ID esteEsOtro1
TOKEN: VAR $_esteEsOtro2
TOKEN: RESERVED ?>

